package extractor

import (
	"bytes"
	"context"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/JohanLindvall/HeapLeach/internal/config"
	"github.com/JohanLindvall/HeapLeach/internal/httpx"
	"github.com/JohanLindvall/HeapLeach/internal/util"
)

// Feeds resolves a syndication feed into the files it attaches: an RSS 2.0
// <enclosure>, or an Atom <link rel="enclosure">. That one element is how
// every podcast on the open web publishes its audio, and it is the whole of
// what this reads — the rest of a feed describes articles.
//
// Two things set it apart from the other extractors here. There is no host to
// match on: a feed is served from wherever the publisher keeps it, so this
// matches the *shape* of a URL instead, which is a guess rather than a fact.
// And the document is XML rather than a page, so it is parsed with
// encoding/xml rather than the HTML parser. Both decide the failure modes:
//
//   - A URL that looks like a feed and is not one — a sitemap, an API dump,
//     an OPML file — is handed to the fallback extractor and downloaded as
//     the file it is, exactly as it would have been had this never matched.
//     Guessing wrong therefore costs one request, not a failed job.
//   - The parser runs non-strict with the HTML entity table, because feeds
//     are generated by a thousand different tools and a bare &nbsp; in one
//     episode's show notes is a hard error in strict XML. Losing a twenty-
//     year archive to one character in a description nobody reads would be
//     absurd, and none of that markup is anywhere near an enclosure.
//
// The enclosure's length attribute is an exact byte count written by the
// publisher's own tooling, not a figure a listing page rounded for display,
// so it is carried as an exact Size and an episode already on disk is skipped
// before a connection is opened. A publisher that splices adverts in at
// request time serves something longer than it advertised; the only
// consequence is that the file is fetched.
type Feeds struct {
	client *httpx.Client
}

// feedAccept asks for a feed by name. Some hosts serve the subscribe page to
// a client that will take anything and the document itself to one that asks
// for it, so this is worth stating rather than leaving at */*.
const feedAccept = "application/rss+xml, application/atom+xml, application/xml;q=0.9, text/xml;q=0.9, */*;q=0.8"

// feedSniffLimit bounds how much of a body is examined to decide whether it
// is a feed at all. The root element is within the first few hundred bytes of
// any real one; anything past this is a document that opens with something
// else entirely.
const feedSniffLimit = 8 << 10

// NewFeeds builds the syndication-feed extractor.
func NewFeeds(client *httpx.Client) *Feeds { return &Feeds{client: client} }

func (f *Feeds) Name() string { return "feed" }

// Feed-shaped URLs. None of these is a promise — the document itself settles
// it — so they are deliberately the shapes publishers actually use rather
// than the narrowest set that could not be wrong.
var (
	// feedHostPrefixes are the subdomains feeds are parked on.
	feedHostPrefixes = []string{"feeds.", "feed.", "rss."}
	// feedPathNames are the path segments a feed is published under.
	feedPathNames = []string{"feed", "feeds", "rss", "atom"}
	// feedFileExtensions name a feed document directly.
	feedFileExtensions = []string{".rss", ".atom", ".xml"}
)

// Match recognises a URL that looks like a feed.
//
// This is the only extractor here whose Match cannot be sure, because a feed
// has no host of its own. It is registered last for that reason: every named
// host is asked first, and what reaches this is a URL nobody claimed.
func (f *Feeds) Match(u *url.URL) bool {
	host := strings.ToLower(u.Hostname())
	for _, prefix := range feedHostPrefixes {
		if strings.HasPrefix(host, prefix) {
			return true
		}
	}

	segs := util.PathSegments(u)
	for _, seg := range segs {
		if slices.Contains(feedPathNames, strings.ToLower(seg)) {
			return true
		}
	}
	if len(segs) > 0 {
		if ext := strings.ToLower(path.Ext(segs[len(segs)-1])); slices.Contains(feedFileExtensions, ext) {
			return true
		}
	}

	// WordPress and everything that copied it ask for a feed by parameter.
	_, wordpress := u.Query()["feed"]
	return wordpress
}

// Extract reads the feed and lists its enclosures.
func (f *Feeds) Extract(ctx context.Context, u *url.URL, opts Options) (*Result, error) {
	body, contentType, err := f.fetch(ctx, u)
	if err != nil {
		return nil, fmt.Errorf("feed: fetch %s: %w", u.Redacted(), err)
	}

	if !feedish(contentType, body) {
		// The guess was wrong: this is a file like any other, and the
		// fallback extractor is what makes a file of a URL nobody claimed.
		// Handing it there is what would have happened had Match been able
		// to tell the difference without asking the server.
		return NewDirect(f.client).Extract(ctx, u, opts)
	}

	return feedResult(body, u)
}

// fetch reads the document and reports the type it was served as.
//
// GetString would be shorter but discards the response headers, and the
// declared content type is half of how a feed is recognised — see feedish.
func (f *Feeds) fetch(ctx context.Context, u *url.URL) (body []byte, contentType string, err error) {
	req, err := f.client.NewRequest(ctx, http.MethodGet, u.String(), nil)
	if err != nil {
		return nil, "", err
	}
	req.Header.Set(httpx.HeaderAccept, feedAccept)

	resp, err := f.client.Do(req)
	if err != nil {
		return nil, "", err
	}
	defer resp.Body.Close()

	body, err = io.ReadAll(io.LimitReader(resp.Body, config.MaxResponseBytes))
	if err != nil {
		return nil, "", fmt.Errorf("read body: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, "", fmt.Errorf("%s", resp.Status)
	}
	return body, resp.Header.Get(httpx.HeaderContentType), nil
}

// feedContentTypes are the types that settle the question on their own.
var feedContentTypes = []string{
	"application/rss+xml",
	"application/atom+xml",
	"application/x-rss+xml",
	"application/x-atom+xml",
}

// feedish reports whether what came back is a syndication feed.
//
// Both halves are needed, and each covers the other's blind spot. A server
// that names one of the feed types is believed outright, because a great many
// feeds are otherwise served as text/xml, as text/plain, or as whatever the
// cache in front of them invented — and a host that declares RSS and then
// serves rubbish should fail loudly rather than have its rubbish quietly
// downloaded. The other direction is why the body is looked at at all:
// sitemaps, API dumps and OPML files are every bit as much application/xml as
// a feed is.
//
// The body half asks the parser for the first element rather than searching
// the text for "<?xml" and "<rss". Feeds omit the prolog often enough, and
// the substring test cannot tell a document from a page that merely mentions
// one, whereas the root element is exactly the question being asked.
func feedish(contentType string, body []byte) bool {
	if slices.Contains(feedContentTypes, feedMediaType(contentType)) {
		return true
	}
	switch feedRoot(body) {
	case "rss", "feed":
		return true
	}
	return false
}

// feedRoot returns the lower-cased local name of the document's first
// element, or "" when there is none to read. The namespace is ignored: Atom
// declares one and RSS does not, and neither fact is worth acting on.
func feedRoot(body []byte) string {
	dec := feedDecoder(body[:min(len(body), feedSniffLimit)])
	for {
		tok, err := dec.Token()
		if err != nil {
			return ""
		}
		if start, ok := tok.(xml.StartElement); ok {
			return strings.ToLower(start.Name.Local)
		}
	}
}

// feedMediaType strips the parameters from a Content-Type or a type attribute,
// which arrive with charsets and codecs appended often enough to matter.
func feedMediaType(value string) string {
	main, _, _ := strings.Cut(value, ";")
	return strings.ToLower(strings.TrimSpace(main))
}

// feedResult parses a feed document into a job.
func feedResult(body []byte, u *url.URL) (*Result, error) {
	var doc feedDocument
	err := feedDecoder(body).Decode(&doc)

	files := feedFiles(&doc, u)
	// A document cut short in transit still lists everything that arrived:
	// the decoder fills the struct as it goes, and an enclosure is a single
	// self-closed element, so what was recovered is whole entries rather
	// than fragments. Turning one dropped connection into no download at all
	// would be the worse answer — but a document that yielded nothing is
	// reported as the parse failure it is.
	if err != nil && len(files) == 0 {
		return nil, fmt.Errorf("feed: parse %s: %w", u.Redacted(), err)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("feed: %s attaches no files — an article feed links to pages "+
			"rather than enclosing media, so there is nothing here to download", u.Redacted())
	}

	return &Result{Title: util.FirstNonEmpty(doc.title(), strings.Trim(u.Path, "/")), Files: files}, nil
}

// feedFiles turns the parsed document into the download list.
func feedFiles(doc *feedDocument, u *url.URL) []File {
	var kept []feedEnclosure
	seen := make(map[string]bool)
	for _, enc := range doc.enclosures() {
		link := resolveRef(u, enc.url)
		// A feed that attaches the same file to two entries — a re-run, a
		// corrected post — would otherwise queue the same bytes twice.
		if link == "" || seen[link] {
			continue
		}
		seen[link] = true
		enc.url = link
		kept = append(kept, enc)

		// A show twenty years deep is a nine-hundred-file job from one
		// paste, so the list is capped. What the cap drops is the far end of
		// the back catalogue rather than last week's episodes, because a
		// feed is newest-first and the cut is made before reversing:
		// dropping the newest instead would mean a second run months later
		// fetched the same oldest N again and never reached anything new.
		if len(kept) == config.MaxListingFiles {
			break
		}
	}
	// Reversed, because a feed is published newest-first and an archive is
	// wanted oldest-first: the queue then runs in the order the show was
	// made, and an interrupted run resumes where the story left off.
	slices.Reverse(kept)

	used := make(map[string]int, len(kept))
	files := make([]File, 0, len(kept))
	for _, enc := range kept {
		files = append(files, File{
			Name: feedFileName(enc.title, enc.url, enc.media, used),
			URL:  enc.url,
			Size: feedLength(enc.length),
			// No headers: an enclosure is published to be fetched by any
			// podcast client in the world, and the analytics redirectors in
			// front of one care about nothing but the user agent, which the
			// shared client already sends.
		})
	}
	return files
}

// feedLength reads the enclosure's byte count.
//
// Unlike the sizes scraped off a listing page elsewhere in this package it is
// exact, which is what makes it worth carrying: the downloader can see that
// an episode is already on disk at that exact length and skip it without
// connecting. A feed that omits the attribute, writes 0, or writes something
// that is not a number at all is saying the same thing in three ways — and
// whole hosting platforms say it, megaphone writing length="0" on every
// episode it serves, so an unknown length is the ordinary case rather than
// the broken one.
func feedLength(raw string) int64 {
	n, err := strconv.ParseInt(strings.TrimSpace(raw), 10, 64)
	if err != nil || n <= 0 {
		return -1
	}
	return n
}

// feedSlashes folds the separators out of an episode title.
//
// SafeName has to treat a slash as a path separator and keeps only what
// follows the last one, so "S2E4: Vinyl / Digital" would land on disk as
// "Digital". Here the difference is still known: this is prose, not a path.
var feedSlashes = strings.NewReplacer("/", "-", `\`, "-")

// feedFileName names the saved file after the episode.
//
// The title is what a listener recognises, so that is the name; the extension
// has to come from elsewhere, since a title carries none. Where from is the
// interesting part. These URLs are routinely wrapped by analytics
// redirectors, which prepend their own path — a tracker's hostname, then
// "redirect.mp3", then the publisher's real URL — so it is the *last* path
// segment that is the publisher's own filename and the first that is the
// tracker's. Nothing is resolved to find that out, and nothing needs to be: a
// redirector wraps rather than replaces, so the real name is already there,
// at the end.
func feedFileName(title, link, mediaType string, used map[string]int) string {
	base := util.NameFromURL(link)
	name := strings.TrimSpace(feedSlashes.Replace(strings.TrimSpace(title)))
	if name == "" {
		name = base
	}
	if name == "" {
		name = "episode"
	}
	if ext := feedExtension(base, mediaType); ext != "" && !strings.EqualFold(path.Ext(name), ext) {
		name += ext
	}
	return feedUnique(used, name)
}

// feedTypeExt maps the media types feeds publish to a file extension.
//
// mime.ExtensionsByType is not used for this. It answers from the system's
// mime.types, so the name a download lands under would depend on which
// distribution the binary happens to be running on — and for audio/mpeg, the
// answer it offers first is ".mp2".
var feedTypeExt = map[string]string{
	"audio/mpeg":           ".mp3",
	"audio/mp3":            ".mp3",
	"audio/mp4":            ".m4a",
	"audio/x-m4a":          ".m4a",
	"audio/aac":            ".aac",
	"audio/aacp":           ".aac",
	"audio/ogg":            ".ogg",
	"audio/vorbis":         ".ogg",
	"audio/opus":           ".opus",
	"audio/flac":           ".flac",
	"audio/x-flac":         ".flac",
	"audio/wav":            ".wav",
	"audio/x-wav":          ".wav",
	"video/mp4":            ".mp4",
	"video/x-m4v":          ".m4v",
	"video/quicktime":      ".mov",
	"video/webm":           ".webm",
	"video/x-matroska":     ".mkv",
	"image/jpeg":           ".jpg",
	"image/png":            ".png",
	"application/pdf":      ".pdf",
	"application/epub+zip": ".epub",
	"application/zip":      ".zip",
}

// feedMediaExtensions are the suffixes trusted when the URL itself carries
// one, built from the types above so the two cannot drift apart.
var feedMediaExtensions = func() map[string]bool {
	out := make(map[string]bool, len(feedTypeExt))
	for _, ext := range feedTypeExt {
		out[ext] = true
	}
	// Extensions no type in the table spells, but a publisher writes.
	for _, ext := range []string{".mp2", ".oga", ".m4b", ".aiff", ".wma", ".avi", ".mpg", ".mpeg"} {
		out[ext] = true
	}
	return out
}()

// feedExtension decides what to call the file.
//
// The URL's own extension wins over the declared type, because the type
// attribute is the field publishers are careless with: audio/mpeg is what a
// great many tools emit whatever the file actually is, and an .m4a saved as
// .mp3 confuses every player that trusts the name. The type is consulted
// second, for the wrapped URLs whose final segment is a bare id with no
// suffix at all — that is the case the redirectors create. A suffix that is
// neither a media extension nor a plausible one at all (".php", a trailing
// number) is dropped rather than carried onto the name.
func feedExtension(base, mediaType string) string {
	ext := strings.ToLower(path.Ext(base))
	if feedMediaExtensions[ext] {
		return ext
	}
	if fromType := feedTypeExt[feedMediaType(mediaType)]; fromType != "" {
		return fromType
	}
	if feedPlausibleExt(ext) {
		return ext
	}
	return ""
}

// feedPlausibleExt reports whether a suffix reads as a file extension: short,
// and letters only. It keeps an unusual but real format (".aif", ".spx")
// while rejecting the dotted ids and version numbers URLs are full of.
func feedPlausibleExt(ext string) bool {
	if len(ext) < 3 || len(ext) > 6 || !strings.HasPrefix(ext, ".") {
		return false
	}
	for _, r := range ext[1:] {
		if r < 'a' || r > 'z' {
			return false
		}
	}
	return true
}

// feedUnique keeps two episodes with the same title from writing to one file.
// "Trailer" and "Bonus" recur down a long feed, and the download directory
// has room for one of each.
//
// Only the repeats are numbered, so every other episode keeps exactly the
// name it is published under, and the numbering is assigned after the list
// has been reversed — oldest first — so the first "Bonus" ever published is
// the plain one and the later ones count up from it, which is both the
// chronological reading and the one that stays put as the feed grows.
func feedUnique(used map[string]int, name string) string {
	key := strings.ToLower(name)
	used[key]++
	if n := used[key]; n > 1 {
		ext := path.Ext(name)
		return fmt.Sprintf("%s (%d)%s", strings.TrimSuffix(name, ext), n, ext)
	}
	return name
}

// feedDecoder builds the parser, and is used for both sniffing and parsing so
// the two can never disagree about what the document is.
//
// Strict parsing is off deliberately. Feeds are generated by everything from
// a hand-written template upwards, and a bare &nbsp;, an unescaped ampersand
// in a title or an unclosed <b> in a description are all hard errors to a
// strict parser — none of them anywhere near an enclosure, and any one of
// them enough to lose the whole archive.
func feedDecoder(body []byte) *xml.Decoder {
	dec := xml.NewDecoder(bytes.NewReader(body))
	dec.Strict = false
	dec.Entity = xml.HTMLEntity
	dec.CharsetReader = feedCharset
	return dec
}

// feedCharset accepts the single-byte encodings older feeds still declare.
//
// encoding/xml refuses outright to parse a document whose declared encoding
// is not UTF-8 unless it is handed a reader for it, so without this an
// ISO-8859-1 feed fails completely rather than merely mis-spelling a title.
// Each byte is read as the code point of the same value, which is exactly
// right for ISO-8859-1 and near enough for its neighbours: everything acted
// on here — URLs, lengths, media types — is ASCII in all of them, and the
// only casualty is the odd piece of punctuation in a filename.
func feedCharset(_ string, input io.Reader) (io.Reader, error) {
	raw, err := io.ReadAll(io.LimitReader(input, config.MaxResponseBytes))
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.Grow(len(raw))
	for _, c := range raw {
		b.WriteRune(rune(c))
	}
	return strings.NewReader(b.String()), nil
}

// feedDocument covers both dialects in one struct.
//
// The element names carry no namespace on purpose: encoding/xml then matches
// on the local name alone, which is what lets one document type read an Atom
// feed (namespaced) and an RSS one (not) without asking which arrived. RSS
// 1.0 is not covered — it hangs its items off <rdf:RDF> and attaches them
// with an element from a module that barely outlived the format.
type feedDocument struct {
	// Title is Atom's feed title. RSS keeps its own inside <channel>, so
	// this stays empty there.
	Title   string       `xml:"title"`
	Channel *feedChannel `xml:"channel"`
	Entries []feedEntry  `xml:"entry"`
}

// feedChannel is the RSS 2.0 <channel>.
type feedChannel struct {
	Title string     `xml:"title"`
	Items []feedItem `xml:"item"`
}

// feedItem is one RSS entry. An item may carry more than one enclosure —
// the specification says otherwise, but feeds do it — and each is a file.
type feedItem struct {
	Title      string        `xml:"title"`
	Enclosures []feedAttachA `xml:"enclosure"`
}

// feedAttachA is an RSS <enclosure>. Nothing else in an item is read: the
// media: and itunes: elements alongside it describe artwork and previews,
// and <media:content> in particular is a near-identical decoy carrying a url,
// a type and a length of its own. It is a different element, so it is not
// matched, and that is the whole of why this only ever names one.
type feedAttachA struct {
	URL    string `xml:"url,attr"`
	Type   string `xml:"type,attr"`
	Length string `xml:"length,attr"`
}

// feedEntry is one Atom entry.
type feedEntry struct {
	Title string     `xml:"title"`
	Links []feedLink `xml:"link"`
}

// feedLink is an Atom <link>, of which an entry has several.
type feedLink struct {
	Rel    string `xml:"rel,attr"`
	Href   string `xml:"href,attr"`
	Type   string `xml:"type,attr"`
	Length string `xml:"length,attr"`
}

// feedEnclosure is one attached file, normalised out of either dialect.
type feedEnclosure struct {
	title  string
	url    string
	media  string
	length string
}

// title names the job after the publication.
func (d *feedDocument) title() string {
	if d.Channel != nil {
		return strings.TrimSpace(d.Channel.Title)
	}
	return strings.TrimSpace(d.Title)
}

// enclosures flattens both dialects into one list, in the document's own
// order — which is newest first, and reversed later.
func (d *feedDocument) enclosures() []feedEnclosure {
	var out []feedEnclosure
	if d.Channel != nil {
		for _, item := range d.Channel.Items {
			for _, enc := range item.Enclosures {
				out = append(out, feedEnclosure{
					title: item.Title, url: enc.URL, media: enc.Type, length: enc.Length,
				})
			}
		}
	}
	for _, entry := range d.Entries {
		for _, link := range entry.Links {
			if !feedIsEnclosure(link.Rel) {
				continue
			}
			out = append(out, feedEnclosure{
				title: entry.Title, url: link.Href, media: link.Type, length: link.Length,
			})
		}
	}
	return out
}

// feedIsEnclosure reports whether an Atom link is an attachment.
//
// The relation has to be tested rather than the link's position or its type:
// an entry's other links are the article itself, its comments and its author,
// and a link with no rel at all means "alternate" — the web page — which is
// the one mistake here that would download a page of HTML per episode.
// Atom also permits the registered relation to be written as its full IANA
// URI, which a handful of generators do.
func feedIsEnclosure(rel string) bool {
	rel = strings.ToLower(strings.TrimSpace(rel))
	return rel == "enclosure" || strings.HasSuffix(rel, "/relation/enclosure")
}
