// Command hostlist renders the supported-site inventory as Markdown, so
// README.md can state what the program supports without anyone maintaining
// that list by hand.
//
// A hand-written inventory is wrong within two commits, and wrong in the
// direction that matters: it under-reports, so a reader concludes their host
// is unsupported when it is not. This asks the registry instead. `make hosts`
// writes the output into README.md between two markers, and CI fails when the
// file and the code disagree.
//
// The prose table in README.md is deliberately NOT generated: it explains how
// a handful of interesting hosts resolve, which is a judgement about what
// deserves explaining. Only the inventory is mechanical.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/JohanLindvall/HeapLeach/internal/config"
	"github.com/JohanLindvall/HeapLeach/internal/extractor"
	"github.com/JohanLindvall/HeapLeach/internal/httpx"
)

// The markers the generated section is written between. Everything outside
// them is a person's prose and is left exactly as it was.
const (
	beginMarker = "<!-- BEGIN HOSTS -->"
	endMarker   = "<!-- END HOSTS -->"
)

func main() {
	countOnly := flag.Bool("count", false, "print the number of supported sites and exit")
	write := flag.String("write", "", "rewrite the host section of this Markdown file in place")
	flag.Parse()

	// A registry built with the defaults: no environment additions, since
	// what is documented must be what the program ships with rather than
	// what one machine happens to be configured for.
	cfg := &config.Config{
		UserAgent: config.DefaultUserAgent,
		Language:  config.DefaultLanguage,
	}
	client := httpx.New(cfg.UserAgent, cfg.AcceptLanguage(), 0, 0)
	catalogue := extractor.NewRegistry(cfg, client).Catalogue()

	switch {
	case *countOnly:
		fmt.Println(countSites(catalogue))
	case *write != "":
		if err := rewrite(*write, render(catalogue)); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
		fmt.Printf(">> %s: %d sites\n", *write, countSites(catalogue))
	default:
		if _, err := os.Stdout.WriteString(render(catalogue)); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
	}
}

// rewrite replaces the marked section of a Markdown file, leaving every other
// byte alone. Done here rather than in the Makefile so the whole generator is
// one program in one language, with no shell quoting between the two halves.
func rewrite(path, body string) error {
	doc, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	text := string(doc)

	start := strings.Index(text, beginMarker)
	end := strings.Index(text, endMarker)
	if start < 0 || end < start {
		return fmt.Errorf("%s has no %s / %s markers to write between", path, beginMarker, endMarker)
	}
	updated := text[:start] + beginMarker + "\n" + strings.TrimSpace(body) + "\n" + text[end:]
	if updated == text {
		return nil // already current; leave the mtime alone
	}
	return os.WriteFile(path, []byte(updated), 0o644)
}

// countSites totals the distinct domains, which is the honest headline
// figure: extractors are an implementation detail and one of them can cover
// two dozen boards.
func countSites(catalogue []extractor.HostInfo) int {
	seen := map[string]bool{}
	for _, host := range catalogue {
		for _, site := range host.Sites {
			seen[site] = true
		}
	}
	return len(seen)
}

// render writes the inventory as two Markdown tables: the hosts that name
// their domains, and the ones that recognise a shape instead.
//
// The split is the interesting part of the answer. "Supported sites: 130" is
// not the whole truth when several extractors match an unbounded set, and
// listing those with an empty cell would read as a defect rather than as the
// point.
func render(catalogue []extractor.HostInfo) string {
	var named, shaped []extractor.HostInfo
	for _, host := range catalogue {
		if host.ByShape {
			shaped = append(shaped, host)
			continue
		}
		named = append(named, host)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- Generated by `make hosts`. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "%d sites across %d extractors, plus %d that match by shape "+
		"rather than by host.\n\n", countSites(catalogue), len(named), len(shaped))

	b.WriteString("| Extractor | Sites |\n|---|---|\n")
	for _, host := range named {
		fmt.Fprintf(&b, "| `%s` | %s |\n", host.Name, code(host.Sites))
	}

	b.WriteString("\nAnd these match a URL or document shape, so the set of sites " +
		"they reach is open-ended:\n\n")
	b.WriteString("| Extractor | Recognises |\n|---|---|\n")
	for _, host := range shaped {
		fmt.Fprintf(&b, "| `%s` | %s |\n", host.Name, shapeOf(host.Name))
	}
	return b.String()
}

// shapeOf describes what an open-ended extractor keys off. Kept here rather
// than in the extractor, which has no business carrying documentation prose,
// and short enough that a missing entry is obvious.
func shapeOf(name string) string {
	switch name {
	case "links":
		return "a `links:<url>` prefix — every supported link on the page"
	case "hls":
		return "an adaptive manifest (`.m3u8`), from any host"
	case "fediverse":
		return "an instance publishing `/.well-known/nodeinfo` — Mastodon, Pleroma, Pixelfed, Lemmy, Misskey"
	case "mediawiki":
		return "any wiki with an open `api.php` — Commons, Wikipedia, Fandom"
	case "autoindex":
		return "an open directory listing (Apache, nginx, lighttpd)"
	case "feed":
		return "an RSS or Atom feed, by its enclosures"
	case "direct":
		return "anything else — checked first for a player, a manifest or a known platform"
	}
	return "a document shape"
}

// code renders a site list as inline code, which keeps a table cell of thirty
// domains readable.
func code(sites []string) string {
	out := make([]string, 0, len(sites))
	for _, site := range sites {
		out = append(out, "`"+site+"`")
	}
	return strings.Join(out, ", ")
}
